#!/usr/bin/env python3
"""Generate Phase 3D tables (§41 spec numbering) from results/*.csv.

Table 1 — Database guarantee matrix
Table 2 — Mutation correctness
Table 3 — Crash recovery matrix (Crash point | Ack state | Expected | Observed | Status)
Table 4 — Transaction atomicity
Table 5 — Compaction equivalence
Table 6 — Concurrency
Table 7 — Backup/restore
Table 8 — Memory optimization
Tables 9-11 — retained extras (state machine, filtering, WAL corruption)

Script-generated only — no manual transcription. Run from repo root:
    python3 research/phase3/tables/generate_tables_ph3d.py
"""
import csv, json, os

ROOT = "research/phase3"
RES = os.path.join(ROOT, "results")
TAB = os.path.join(ROOT, "tables")
os.makedirs(TAB, exist_ok=True)


def rd(name):
    with open(os.path.join(RES, name)) as f:
        return list(csv.DictReader(f))


def md_table(path, title, header, rows, note=None):
    with open(path, "w") as f:
        f.write("<!-- script-generated by research/phase3/tables/generate_tables_ph3d.py; do not edit -->\n")
        f.write(f"# {title}\n\n")
        if note:
            f.write(f"{note}\n\n")
        f.write("| " + " | ".join(header) + " |\n")
        f.write("|" + "|".join(["---"] * len(header)) + "|\n")
        for r in rows:
            f.write("| " + " | ".join(str(x) for x in r) + " |\n")
    print("wrote", path)


def clip(s, n=110):
    return (s[:n] + "…") if len(s) > n else s


# Table 1 — Database guarantee matrix (§2)
rows = rd("database-guarantees.csv")
md_table(os.path.join(TAB, "table-1-database-guarantees.md"),
         "Table 1 — Database guarantee matrix (implemented / tested / evidence)",
         ["operation", "intended guarantee", "implemented?", "tested?", "evidence"],
         [[r["operation"], r["intended_guarantee"], r["implemented"], r["tested"],
           r["evidence"]] for r in rows])

# Table 2 — Mutation correctness (§7-10)
rows = rd("mutations.csv")
sm = rd("state-machine.csv")
rows2 = [[r["run_or_check"], r["logged_ops"], r["expected_docs"], r["observed_docs"],
          r["state_equivalence"], r["verdict"]] for r in rows
         if r["run_or_check"].startswith("PH3D")]
rows2 += [[r["run"], "-", "-", "-", "gated checks", f'{int(r["checks_total"]) - int(r["checks_failed"])}/{r["checks_total"]} PASS']
          for r in sm]
md_table(os.path.join(TAB, "table-2-mutation-correctness.md"),
         "Table 2 — Mutation correctness: lifecycle, ID mapping, update semantics (PH3D-MUTATION-001 via parents)",
         ["run / check", "logged ops", "expected docs", "observed docs", "equivalence", "verdict"], rows2)

# Table 3 — Crash recovery matrix in §17 shape (Crash point | Ack state | Expected | Observed | Status)
cr = rd("crash-recovery.csv")
EXPECTED = {
    ("group", "after_acks"): "ALL_ACKED", ("group", "after_flush"): "ALL_ACKED",
    ("group", "after_checkpoint"): "ALL_ACKED", ("group", "mid_inserts"): "ALL_ACKED",
    ("group", "mid_flush"): "ALL_ACKED", ("group", "after_compact"): "ALL_ACKED",
    ("sync", "after_acks"): "ALL_ACKED", ("sync", "after_flush"): "ALL_ACKED",
    ("sync", "after_checkpoint"): "ALL_ACKED", ("sync", "mid_inserts"): "ALL_ACKED",
    ("sync", "mid_flush"): "ALL_ACKED", ("sync", "after_compact"): "ALL_ACKED",
    ("async", "after_acks"): "PREFIX (pre-flush acks not durable)",
    ("async", "mid_inserts"): "PREFIX (pre-flush acks not durable)",
    ("async", "mid_flush"): "PREFIX (pre-flush acks not durable)",
    ("async", "after_compact"): "PREFIX (pre-flush acks not durable)",
    ("async", "after_flush"): "ALL_ACKED", ("async", "after_checkpoint"): "ALL_ACKED",
    ("group", "during_commit_txn"): "ALL_ACKED + txn all-or-nothing",
    ("sync", "during_commit_txn"): "ALL_ACKED + txn all-or-nothing",
    ("async", "during_commit_txn"): "ALL_ACKED baseline; txn all-or-nothing (committed txn may be absent: Async ack semantics)",
}
rows3 = []
for r in cr:
    exp = EXPECTED.get((r["durability"], r["crash_point"]), "?")
    txn = r["txn"]
    is_txn_point = r["crash_point"] == "during_commit_txn"
    if "PARTIAL" in txn:
        status = "MISMATCH"
    elif is_txn_point:
        # baseline must be intact for the mode; txn must be all-or-nothing
        baseline_ok = r["verdict"] in ("ALL_ACKED", "PREFIX")
        txn_ok = ("txn=10/10" in txn) or ("txn=0/10" in txn)
        async_ok = r["durability"] != "async" or "COMMITTED_NOT_DURABLE_ASYNC" in txn or "txn=10/10" in txn
        status = "MATCH" if (baseline_ok and txn_ok and async_ok) else "MISMATCH"
    elif r["verdict"] == exp.split(" ")[0] or (exp.startswith("PREFIX") and r["verdict"] == "PREFIX"):
        status = "MATCH"
    else:
        status = "MISMATCH"
    ack = f'{r["acked_present"]} acked; {r["unacked_present"]} unacked present'
    rows3.append([r["run"].replace("PH3D-", ""), r["durability"], r["crash_point"],
                  ack, exp, f'{r["verdict"]} ({r["acked_present"]}); {txn}', status])
md_table(os.path.join(TAB, "table-3-crash-recovery.md"),
         "Table 3 — Crash recovery matrix (§15-17): 7 crash points × 3 durability modes",
         ["run", "durability", "crash point", "ack state", "expected", "observed", "status"],
         rows3,
         note="Crash points implemented vs §15: mid_inserts≈(2,4,5 during append/apply/index), after_acks≈3, "
              "mid_flush≈6, after_flush≈7, after_checkpoint≈8+10 (post), after_compact≈9 (post), "
              "during_commit_txn≈3 on the txn path. Points 1 (pre-append) and mid-checkpoint/mid-compaction "
              "windows are not separately instrumented — see methodology/ph3d-spec-deviations.md.")

# Table 4 — Transaction atomicity (§18-21)
rows = rd("transactions.csv")
md_table(os.path.join(TAB, "table-4-transaction-atomicity.md"),
         "Table 4 — Transaction atomicity (PH3D-TX-001; crash legs in PH3D-CRASH-*)",
         ["check", "ok", "detail"],
         [[r["check"], r["ok"], clip(r["detail"])] for r in rows],
         note="TxnOp = Insert | Delete only (no update op — §21 combos involving update are UNSUPPORTED, documented). "
              "Crash legs: during_commit_txn is 10/10 or 0/10 — never partial — in all 3 durability modes (21/21 points).")

# Table 5 — Compaction equivalence (§26-27)
rows = rd("compaction.csv")
md_table(os.path.join(TAB, "table-5-compaction-equivalence.md"),
         "Table 5 — Compaction equivalence (PH3D-COMPACT-001) + documented live behavior (PH3D-COMPACT-002)",
         ["check", "ok", "detail"],
         [[r["check"], r["ok"], clip(r["detail"])] for r in rows])

# Table 6 — Concurrency (§22-24)
rows = rd("concurrency.csv")
md_table(os.path.join(TAB, "table-6-concurrency.md"),
         "Table 6 — Concurrency: read ladder (w=0), mixed matrix, deterministic-log replay (latency µs)",
         ["run", "r", "w", "queries", "p50", "p95", "p99", "QPS", "errors", "checker", "warnings"],
         [[r["run"].replace("PH3D-", ""), r["readers"], r["writers"], r["queries"],
           r["p50_us"], r["p95_us"], r["p99_us"], r["qps"], r["errors"],
           r["checker_clean"], r["checker_warnings"]] for r in rows],
         note="PH3D-CONC-003 rows: replay_exact_state 450 docs EXACT vs merged op logs; contention 100 keys, 0 torn records. "
              "No linearizability claim (§25): ordering = mutation-gate serialized, per-key last-write-wins.")

# Table 7 — Backup/restore (§28-30)
rows = rd("backup-restore.csv")
md_table(os.path.join(TAB, "table-7-backup-restore.md"),
         "Table 7 — Backup/restore: equivalence (BACKUP-001), inventory + checksum integrity (BACKUP-002)",
         ["run", "check", "ok", "detail"],
         [[r["run"].replace("PH3D-", ""), r["check"], r["ok"], clip(r["detail"])] for r in rows],
         note="No online backup (§30): copies are uncoordinated with the mutation gate; quiescent database required (documented).")

# Table 8 — Memory optimization (§36-38)
rows = rd("memory-optimization.csv")
md_table(os.path.join(TAB, "table-8-memory-optimization.md"),
         "Table 8 — Memory optimization status (§36-38)",
         list(rows[0].keys()), [[("" if v is None else str(v)) for v in r.values()] for r in rows],
         note="Optional family PH3D-MEM-OPT-001 not run: no before/after memory claim exists. "
              "Figure slots 4/5 of §42 deliberately unproduced (no data backing).")

# Tables 9-11 — retained extras
rows = rd("state-machine.csv")
md_table(os.path.join(TAB, "table-9-state-machine.md"),
         "Table 9 — Model-based state-machine suite (§33)",
         ["run", "seed", "ops", "checks", "failed", "filter tests", "filter failed", "verdict"],
         [[r["run"].replace("PH3D-", ""), r["seed"], r["ops"], r["checks_total"],
           r["checks_failed"], r["filter_tests"], r["filter_failures"], r["verdict"]] for r in rows])

rows = rd("filtering.csv")
md_table(os.path.join(TAB, "table-10-filtering.md"),
         "Table 10 — Filter semantics: soundness/determinism gates + measured recall (PH3D-FILTER-001)",
         ["check", "sound + deterministic", "measured recall"],
         [[r["check"], r["sound_and_deterministic"], r["measured_recall"]] for r in rows])

rows = rd("wal-replay.csv")
md_table(os.path.join(TAB, "table-11-wal-corruption.md"),
         "Table 11 — WAL corruption handling (§14: detect + report; no silent recovery)",
         ["mode", "outcome", "recovered docs", "checker clean", "note"],
         [[r["corruption_mode"], r["outcome"], r["recovered_docs"] or "—",
           r["checker_clean"] or "—", r["note"]] for r in rows])
print("done")
