.PHONY: build test run-example clippy fmt clean

build:
	cargo build

test:
	cargo test

run-example:
	cargo run --example basic_usage

clippy:
	cargo clippy -- -D warnings

fmt:
	cargo fmt

clean:
	cargo clean
